"""
=============================================================================
TextGrid Generator for Ultrasound Video and Stimulus Logs
=============================================================================

Description:
------------
This script generates Praat TextGrid files by combining timing information 
from two separate log files: an ultrasound video recording log and a stimulus 
display log. It matches the absolute timestamps of successfully displayed 
stimuli to their corresponding video files and calculates the relative 
start and end times to create an IntervalTier within a TextGrid.

Prerequisites & Installation:
-----------------------------
Python 3.x must be installed on your system.
The following external Python libraries are required:
  - pandas (for efficient data manipulation and log reading)
  - textgrid (for constructing and exporting Praat TextGrid objects)

To install the required libraries, open your terminal or command prompt 
and run the following command:
    pip install pandas textgrid

Input Files Expected:
---------------------
1. Video Log ('_MewRecorder.log'):
   - Generated by the 'MewRecorder' app (https://github.com/WeirongChen/MewRecorder).
   - Tab-delimited text file.
   - Columns expected: [video file name, absolute start time, absolute end time, status, empty]
   - Time format expected: HH:MM:SS.sss (e.g., 16:53:42.458)
   - Example:
     recording_2026-04-11_16-53-42-458	16:53:42.458	17:01:25.356	success-US-audio	
     recording_2026-04-11_17-01-52-629	17:01:52.629	17:08:33.120	success-US-audio
   
2. Stimulus Log ('_TimeLog.log'):
   - Generated by the 'WordlistRecord' app (https://github.com/WeirongChen/WordlistRecord).
   - Tab-delimited text file generated by Excel VBA (UTF-16 encoding).
   - The first 4 rows are considered metadata and are skipped.
   - Columns expected: [stimulus ID, absolute start, absolute end, relative start, relative end, duration, success flag]
   - Time format expected: HH:MM:SS:ms (e.g., 16:56:52:5). 
     Note: The script automatically handles the irregular colon ':' millisecond delimiter and missing zero-padding.
   - Example:
     Trial Date	2026-04-11					
     Trial Start	16:53:28:850					
     Recording Start	0001	16:53:28:865				
     StartBeep	16:53:28:885	16:53:28:885	0.02	0.02	0	
     C001	16:53:29:555	16:53:32:536	0.69	3.671	2.981	
     C001	16:53:46:768	16:54:37:967	17.903	69.102	51.199	C001
     C002	16:55:21:251	16:56:11:357	112.386	162.492	50.106	C002
     D001	16:56:42:478	16:56:51:518	193.613	202.653	9.04	
     D001	16:56:52:5	16:56:57:651	203.14	208.786	5.646	D001

Output:
-------
- A directory named 'output_textgrids' will be created in the current working directory.
- For each valid video, a '.TextGrid' file is generated inside this directory.
- Each TextGrid contains a single IntervalTier named 'stimulus' that aligns the stimuli text with the video timing.

Usage Instructions:
-------------------
0. Copy '_TimeLog.log' from the WordlistRecord output folder and place it in the MewRecorder recording folder.
1. Place this script ('merge_MewRecorder_WordlistRecord_logs_to_textgrid.py') in the same directory as your 
   input log files ('_MewRecorder.log' and '_TimeLog.log').
2. Open your terminal (e.g., Anaconda Prompt, Command Prompt, or Terminal).
3. Navigate to the folder containing these files using the `cd` command.
   Example: cd C:\MewRecorder_recordings\
4. Run the script by typing:
   python merge_MewRecorder_WordlistRecord_logs_to_textgrid.py
5. Check the 'output_textgrids' folder for your generated files.
=============================================================================
"""

import pandas as pd
import textgrid
import os
from datetime import datetime, timedelta

def parse_time_string(time_str, is_stim_log=False):
    """
    Standardizes timestamp strings into datetime objects.
    Handles the difference in millisecond delimiters (. vs :) and missing padding.
    """
    if pd.isna(time_str):
        return None
        
    time_str = str(time_str).strip()
    
    if is_stim_log:
        # _TimeLog.log format: HH:MM:SS:ms (e.g. 16:56:52:5)
        parts = time_str.split(':')
        if len(parts) == 4:
            h, m, s, ms = parts
            # Ensure ms is zero-padded to 3 digits (e.g., '5' -> '005')
            time_str = f"{h}:{m}:{s}.{int(ms):03d}"
            
    # Parse to datetime object using an arbitrary date (1900-01-01) 
    # since we only care about time differences
    return datetime.strptime(time_str, "%H:%M:%S.%f")

def generate_textgrids(video_log_path, stim_log_path, output_dir="output_textgrids"):
    """
    Generates Praat TextGrid files from video recording and stimulus display logs.
    
    Args:
        video_log_path (str): Path to '_MewRecorder.log'
        stim_log_path (str): Path to '_TimeLog.log'
        output_dir (str): Directory where TextGrid files will be saved
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Load Video Log (_MewRecorder.log)
    df_video = pd.read_csv(video_log_path, sep='\t', header=None,
                           names=['video_file', 'start_time', 'end_time', 'status', 'empty'])
    
    # Process video times
    df_video['start_dt'] = df_video['start_time'].apply(lambda x: parse_time_string(x, False))
    df_video['end_dt'] = df_video['end_time'].apply(lambda x: parse_time_string(x, False))
    df_video['duration'] = (df_video['end_dt'] - df_video['start_dt']).dt.total_seconds()
    
    # 2. Load Stimulus Log (_TimeLog.log)
    # Skip first 4 rows of metadata
    # Added encoding='utf-16' to handle Excel VBA text export format
    df_stim = pd.read_csv(stim_log_path, sep='\t', skiprows=4, header=None,
                          encoding='utf-16',
                          names=['stimulus', 'abs_start', 'abs_end', 'rel_start', 'rel_end', 'duration', 'success', 'empty'])
    
    # Filter only successful recordings (7th column is not null)
    df_stim = df_stim.dropna(subset=['success'])
    
    # Process stimulus absolute times
    df_stim['start_dt'] = df_stim['abs_start'].apply(lambda x: parse_time_string(x, True))
    df_stim['end_dt'] = df_stim['abs_end'].apply(lambda x: parse_time_string(x, True))
    
    # 3. Match Stimuli to Video Files and Create TextGrids
    for _, video in df_video.iterrows():
        if pd.isna(video['start_dt']):
            continue
            
        video_start = video['start_dt']
        video_end = video['end_dt']
        vid_duration = video['duration']
        
        # Find stimuli strictly within this video's timeframe
        mask = (df_stim['start_dt'] >= video_start) & (df_stim['end_dt'] <= video_end)
        vid_stimuli = df_stim[mask]
        
        # Create TextGrid object
        tg = textgrid.TextGrid(minTime=0.0, maxTime=vid_duration)
        stim_tier = textgrid.IntervalTier(name='stimulus', minTime=0.0, maxTime=vid_duration)
        
        # Add intervals to tier
        for _, stim in vid_stimuli.iterrows():
            # Calculate relative offset in seconds
            rel_start_sec = (stim['start_dt'] - video_start).total_seconds()
            rel_end_sec = (stim['end_dt'] - video_start).total_seconds()
            
            # Avoid duplicate or overlapping intervals
            stim_tier.add(minTime=rel_start_sec, maxTime=rel_end_sec, mark=str(stim['stimulus']))
            
        # Add the tier to the TextGrid
        tg.append(stim_tier)
        
        # 4. Save output file
        output_file = os.path.join(output_dir, f"{video['video_file']}.TextGrid")
        tg.write(output_file)
        print(f"Generated {output_file} with {len(vid_stimuli)} intervals.")

# Execute the script
if __name__ == "__main__":
    print("Starting TextGrid generation...")
    # Make sure the log files are in the same folder as this Python script
    generate_textgrids('_MewRecorder.log', '_TimeLog.log')
    print("Process complete! Check the 'output_textgrids' folder.")